const HOMETYPES='HOMETYPES'
const GETLOCATION='GETLOCATION'
const GETSHOPSLIST='GETSHOPSLIST'
const SEARCHSHOP ='SEARCHSHOP'
export {
    HOMETYPES,
    GETLOCATION,
    GETSHOPSLIST,
    SEARCHSHOP
}